## Preprocessing

In [15]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

**Target variables**: 'IS_SUCCESSFUL'

**Feature variables**: 'APPLICATION_TYPE', 'AFFILIATION', 'CLASSIFICATION', 'USE_CASE', 'ORGANIZATION', 'INCOME_AMT', 'ASK_AMT', 'SPECIAL CONSIDERATIONS'

In [17]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME' as well as columns 'STATUS' and 'SPECIAL_CONSIDERATIONS'
application_df = application_df.drop(['EIN', 'NAME', 'STATUS', 'SPECIAL_CONSIDERATIONS'], axis=1)
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,INCOME_AMT,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,0,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1-9999,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,0,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,10000-24999,6692,1
4,T3,Independent,C1000,Heathcare,Trust,100000-499999,142590,1
...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,0,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,0,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,0,5000,0
34297,T5,Independent,C3000,ProductDev,Association,0,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1M-5M,36500179,0

In [18]:
# Generate a categorical variable list
application_cat = application_df.dtypes[application_df.dtypes == "object"].index.to_list()

# Determine the number of unique values in each categorical column.
application_df[application_cat].nunique()

APPLICATION_TYPE    17
AFFILIATION          6
CLASSIFICATION      71
USE_CASE             5
ORGANIZATION         4
INCOME_AMT           9
dtype: int64

In [19]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE      17
AFFILIATION            6
CLASSIFICATION        71
USE_CASE               5
ORGANIZATION           4
INCOME_AMT             9
ASK_AMT             8747
IS_SUCCESSFUL          2
dtype: int64

In [20]:
# Look at APPLICATION_TYPE value counts for binning
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [21]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = ['T9', 'T13', 'T12', 'T2', 'T25', 'T14', 'T29', 'T15', 'T17']

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [22]:
# Look at CLASSIFICATION value counts for binning
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [23]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
value_counts = application_df['CLASSIFICATION'].value_counts()
classifications_to_replace = value_counts[value_counts < 700].index.tolist()

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
Other     1484
C7000      777
Name: count, dtype: int64

In [24]:
# Using OneHotEncoder to encode categorical data
# Creating a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

# Fit and transform the OneHotEncoder using the categorical variable list
encode_df = pd.DataFrame(enc.fit_transform(application_df[application_cat]))

# Add the encoded variable names to the dataframe
encode_df.columns = enc.get_feature_names_out(application_cat)
encode_df.head()

/Users/samwallach/Documents/BootCamp/Module_3_Python/.venv/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,APPLICATION_TYPE_T8,AFFILIATION_CompanySponsored,...,ORGANIZATION_Trust,INCOME_AMT_0,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [25]:
# Merging the encoded variables to the original dataframe
application_df = application_df.merge(encode_df, left_index=True, right_index=True)
application_df = application_df.drop(application_cat, axis=1)
application_df.head()

,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,...,ORGANIZATION_Trust,INCOME_AMT_0,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M
0,5000,1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,108590,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,5000,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,6692,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,142590,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [26]:
# Split our preprocessed data into our features and target arrays
y = application_df['IS_SUCCESSFUL']
X = application_df.drop(columns="IS_SUCCESSFUL")

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, stratify=y)

In [27]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [28]:
# Create a StandardScaler instances
X_scaler = StandardScaler()

# Fit the StandardScaler
X_scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [29]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = X_train_scaled.shape[1]
hidden_nodes_layer1 = 80
hidden_nodes_layer2 = 30

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

/Users/samwallach/Documents/BootCamp/Module_3_Python/.venv/lib/python3.9/site-packages/keras/src/layers/core/dense.py:88: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 80)             │         3,360 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 30)             │         2,430 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            31 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 5,821 (22.74 KB)

 Trainable params: 5,821 (22.74 KB)

 Non-trainable params: 0 (0.00 B)

In [30]:
# Compile the model
nn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [31]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 905us/step - accuracy: 0.7060 - loss: 0.5853
Epoch 2/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 881us/step - accuracy: 0.7332 - loss: 0.5504
Epoch 3/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 883us/step - accuracy: 0.7303 - loss: 0.5516
Epoch 4/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 896us/step - accuracy: 0.7302 - loss: 0.5482
Epoch 5/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 879us/step - accuracy: 0.7367 - loss: 0.5443
Epoch 6/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 878us/step - accuracy: 0.7309 - loss: 0.5455
Epoch 7/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 939us/step - accuracy: 0.7360 - loss: 0.5463
Epoch 8/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 894us/step - accuracy: 0.7370 - loss: 0.5423
Epoch 9/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 916us/step - accuracy: 0.7334 - loss: 0.5433
Epoch 10/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 892us/step - accuracy: 0.7317 - loss: 0.5425
Epoch 11/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 993us/step - accuracy: 0.7341 - loss: 0.5427
Epoch 12/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 909us/step - accuracy: 0.7335 - loss: 0.5458
Epoch 13/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 932us/step - accuracy: 0.7377 - loss: 0.5418
Epoch 14/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 886us/step - accuracy: 0.7408 - loss: 0.5386
Epoch 15/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 896us/step - accuracy: 0.7319 - loss: 0.5434
Epoch 16/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 920us/step - accuracy: 0.7329 - loss: 0.5409
Epoch 17/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 963us/step - accuracy: 0.7402 - loss: 0.5351
Epoch 18/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 935us/step - accuracy: 0.7352 - loss: 0.5412
Epoch 19/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 893us/step - accuracy: 0.7391 - loss: 0.5377
Epoch 20/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 934us/step - accuracy: 0.7407 - loss: 0.5344
Epoch 21/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 905us/step - accuracy: 0.7374 - loss: 0.5394
Epoch 22/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 917us/step - accuracy: 0.7399 - loss: 0.5349
Epoch 23/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 922us/step - accuracy: 0.7379 - loss: 0.5406
Epoch 24/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 919us/step - accuracy: 0.7379 - loss: 0.5399
Epoch 25/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 930us/step - accuracy: 0.7388 - loss: 0.5386
Epoch 26/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 978us/step - accuracy: 0.7273 - loss: 0.5457
Epoch 27/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 927us/step - accuracy: 0.7379 - loss: 0.5393
Epoch 28/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 889us/step - accuracy: 0.7368 - loss: 0.5364
Epoch 29/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 934us/step - accuracy: 0.7381 - loss: 0.5371
Epoch 30/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 914us/step - accuracy: 0.7391 - loss: 0.5371
Epoch 31/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 895us/step - accuracy: 0.7364 - loss: 0.5402
Epoch 32/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 909us/step - accuracy: 0.7383 - loss: 0.5406
Epoch 33/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 998us/step - accuracy: 0.7416 - loss: 0.5338
Epoch 34/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 929us/step - accuracy: 0.7360 - loss: 0.5358
Epoch 35/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 906us/step - accuracy: 0.7337 - loss: 0.5384
Epoch 36/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 975us/step - accuracy: 0.7374 - loss: 0.5357
Epoch 37/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 924us/step - accuracy: 0.7412 - loss: 0.5340
Epoch 38/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 920us/step - accuracy: 0.7384 - loss: 0.5372
Epoch 39/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 902us/step - accuracy: 0.7379 - loss: 0.5373
Epoch 40/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 926us/step - accuracy: 0.7372 - loss: 0.5375
Epoch 41/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 988us/step - accuracy: 0.7393 - loss: 0.5353
Epoch 42/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 907us/step - accuracy: 0.7391 - loss: 0.5335
Epoch 43/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 916us/step - accuracy: 0.7350 - loss: 0.5402
Epoch 44/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 903us/step - accuracy: 0.7403 - loss: 0.5322
Epoch 45/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 915us/step - accuracy: 0.7372 - loss: 0.5389
Epoch 46/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 914us/step - accuracy: 0.7353 - loss: 0.5386
Epoch 47/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 933us/step - accuracy: 0.7365 - loss: 0.5363
Epoch 48/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 980us/step - accuracy: 0.7348 - loss: 0.5400
Epoch 49/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 923us/step - accuracy: 0.7410 - loss: 0.5362
Epoch 50/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 905us/step - accuracy: 0.7369 - loss: 0.5381
Epoch 51/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 907us/step - accuracy: 0.7421 - loss: 0.5333
Epoch 52/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 924us/step - accuracy: 0.7390 - loss: 0.5344
Epoch 53/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 903us/step - accuracy: 0.7385 - loss: 0.5368
Epoch 54/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7442 - loss: 0.5309
Epoch 55/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 912us/step - accuracy: 0.7357 - loss: 0.5381
Epoch 56/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 949us/step - accuracy: 0.7385 - loss: 0.5342
Epoch 57/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 901us/step - accuracy: 0.7383 - loss: 0.5349
Epoch 58/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 916us/step - accuracy: 0.7455 - loss: 0.5274
Epoch 59/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 897us/step - accuracy: 0.7452 - loss: 0.5269
Epoch 60/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7390 - loss: 0.5355
Epoch 61/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 904us/step - accuracy: 0.7427 - loss: 0.5288
Epoch 62/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 901us/step - accuracy: 0.7396 - loss: 0.5326
Epoch 63/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 917us/step - accuracy: 0.7373 - loss: 0.5360
Epoch 64/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 915us/step - accuracy: 0.7416 - loss: 0.5326
Epoch 65/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 935us/step - accuracy: 0.7377 - loss: 0.5335
Epoch 66/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7398 - loss: 0.5355
Epoch 67/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7428 - loss: 0.5323
Epoch 68/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7407 - loss: 0.5325
Epoch 69/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 936us/step - accuracy: 0.7391 - loss: 0.5340
Epoch 70/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 925us/step - accuracy: 0.7402 - loss: 0.5334
Epoch 71/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 938us/step - accuracy: 0.7432 - loss: 0.5313
Epoch 72/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 920us/step - accuracy: 0.7440 - loss: 0.5301
Epoch 73/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 981us/step - accuracy: 0.7435 - loss: 0.5308
Epoch 74/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 903us/step - accuracy: 0.7400 - loss: 0.5306
Epoch 75/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 934us/step - accuracy: 0.7428 - loss: 0.5330
Epoch 76/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 911us/step - accuracy: 0.7412 - loss: 0.5332
Epoch 77/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 996us/step - accuracy: 0.7385 - loss: 0.5345
Epoch 78/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 916us/step - accuracy: 0.7396 - loss: 0.5329
Epoch 79/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 917us/step - accuracy: 0.7354 - loss: 0.5395
Epoch 80/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 955us/step - accuracy: 0.7400 - loss: 0.5333
Epoch 81/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 927us/step - accuracy: 0.7429 - loss: 0.5327
Epoch 82/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7370 - loss: 0.5315
Epoch 83/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 894us/step - accuracy: 0.7426 - loss: 0.5300
Epoch 84/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 936us/step - accuracy: 0.7367 - loss: 0.5372
Epoch 85/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 906us/step - accuracy: 0.7361 - loss: 0.5350
Epoch 86/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 916us/step - accuracy: 0.7444 - loss: 0.5286
Epoch 87/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 997us/step - accuracy: 0.7411 - loss: 0.5345
Epoch 88/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 959us/step - accuracy: 0.7444 - loss: 0.5269
Epoch 89/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7369 - loss: 0.5351
Epoch 90/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 925us/step - accuracy: 0.7421 - loss: 0.5299
Epoch 91/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 931us/step - accuracy: 0.7371 - loss: 0.5352
Epoch 92/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7412 - loss: 0.5317
Epoch 93/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 925us/step - accuracy: 0.7397 - loss: 0.5333
Epoch 94/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 904us/step - accuracy: 0.7407 - loss: 0.5338
Epoch 95/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 927us/step - accuracy: 0.7434 - loss: 0.5283
Epoch 96/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 910us/step - accuracy: 0.7449 - loss: 0.5275
Epoch 97/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7427 - loss: 0.5315
Epoch 98/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 922us/step - accuracy: 0.7387 - loss: 0.5332
Epoch 99/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 913us/step - accuracy: 0.7399 - loss: 0.5318
Epoch 100/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 914us/step - accuracy: 0.7410 - loss: 0.5332

In [32]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - 1ms/step - accuracy: 0.7303 - loss: 0.5616
Loss: 0.561566174030304, Accuracy: 0.7302623987197876

In [33]:
# Export our model to HDF5 file
nn.save("AlphabetSoupCharity_Optimization_1.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.